services:
  nginx:
    image: nginx:alpine
    ports:
      - "180:80"
    networks:
      - mynet

  ssh:
    image: linuxserver/openssh-server
    ports:
      - "122:2222"
    environment:
      - PASSWORD_ACCESS=true
      - USER_PASSWORD=testpass
      - USER_NAME=testuser
    networks:
      - mynet

  tcp:
    image: alpine
    command: sh -c "nc -lk -p 150"
    ports:
      - "150:150"
    networks:
      - mynet

networks:
  mynet:
    ipam:
      config:
        - subnet: 172.20.0.0/24
